import Link from "next/link";
import "../globals.css";
import { Inter } from "next/font/google";
import { getPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My awsome site",
  description: "Generated by me",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href="/" className="luuk">
            Luuk
          </Link>
          <div className="navBar">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="text">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
